# Base configs
baseurl: "https://stephenstewert.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-JVC616BEJX"

# UI configs
title: "Photography by Stephen Stewert"
subtitle: "Welcome"
author: "Stephen Stewert"
header:
 title: "Photography"
 subtitle: "by Stephen Stewert"
footer:
 name: "Hey there, my name is Steve"
 bio: "Biography goes here"
 github: " <a href=\"https://www.buymeacoffee.com/kylewhirl\">buymeacoffee</a>;)"
web_design: "KW"
social_urls:
  instagram: "https://www.instagram.com/stephenstewert"
  github: "https://www.github.com/stephenstewert"
